### ISSUE TITLE
performance benchmark

### ISSUE THREAD

**Issue by Dowwie** [plaitpy/plaitpy#4]
Hey we had a correspondence on HN.  I didn't realize how bad the faker library was until you pointed out the performance issues.  Your benchmark isn't accurate, though, because of how you're timing.
You're not performance benchmarking plait as well as you could be.  Instead, try the "perf" library from pypi:
    pip install perf

Use this gist as a template to run plait through.  The example is intuitive enough that you could figure out what the change for plait:  https://gist.github.com/Dowwie/499d9fb0344d7f4345ff0e669a7d4a36

simply execute the benchmark python script from the command line and perf will run, eventually returning results to stdout

I was curious how much faster a rust binding would be than faker so I started to work on a port. The library currently only generates a fake full name but it won't take much time to port the rest over.

These are the perf results for pyfakers vs faker -- almost 100 times faster using rust and a little bit of cffi overhead:
pyfakers:  Mean +- std dev: 1.73 ms +- 0.08 ms
faker: Mean +- std dev: 127 ms +- 1 ms

what are your plait perf results?

**Comment by okayzed** [comment]
oh, very interesting (and nice work!)
With pypy and python2 (on my i5 laptop): 

```
import perf
from plaitpy.fakerb import decode

def get_names():
    return [decode("#{name.name}") for x in range(10000)]


def run_bench():
    runner = perf.Runner()
    runner.timeit("get_names", "get_names()", "from __main__ import get_names",
                  inner_loops=100)


if __name__ == "__main__":
    run_bench()

"""
Results:
okay@chalk:~/tonka/src/plait.py$ pypy tests/perftest.py
.........
get_names: Mean +- std dev: 2.64 ms +- 0.08 ms

okay@chalk:~/tonka/src/plait.py$ python tests/perftest.py
.....................
WARNING: the benchmark result may be unstable
* the standard deviation (188 us) is 14% of the mean (1.32 ms)

Try to rerun the benchmark with more runs, values and/or loops.
Run 'python -m perf system tune' command to reduce the system jitter.
Use perf stats, perf dump and perf hist to analyze results.
Use --quiet option to hide these warnings.

get_names: Mean +- std dev: 1.32 ms +- 0.19 ms
"""
```

**Comment by okayzed** [comment]
the results are slightly strange, because pypy should be faster than python - so i think there is some aspect in how setup/teardown are performed that is hiding their differences.

```
fields:
  name: "#{name.name}"
okay@chalk:~/tonka/src/plait.py$ time python main.py name.yaml --num 100000 > /dev/null             

real    0m2.553s
user    0m2.536s
sys     0m0.012s
okay@chalk:~/tonka/src/plait.py$ time pypy main.py name.yaml --num 100000 > /dev/null

real    0m0.708s
user    0m0.668s
sys     0m0.036s
okay@chalk:~/tonka/src/plait.py$

```

**Comment by okayzed** [comment]
I've been investigating a little bit, and I think the inner_loops= needs to be calibrated with same value as the loop count in the xrange. I will properly compare python, pypy and pyfakers using the same iter counts

**Comment by okayzed** [comment]
@Dowwie thanks for opening the issue and the example code, i've checked it into src/perftest.py. i'm looking forward to see how pyfakers comes along (and will think about how to integrate it into plait.py as a fake data backend)
